name: Build Resume PDF
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: blang/latex:ubuntu
      options: --user root -v /github/workspace:/workspace
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Compile LaTeX
        run: |
          cd /workspace
          xelatex -interaction=nonstopmode resume.tex
      
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
